adding deploy and remote commands

diff --git a/cobbler b/cobbler
--- a/cobbler
+++ b/cobbler
@@ -38,11 +38,28 @@ export -f require install package
 source $COBBLER_HOME/core/out.sh
 source $COBBLER_HOME/core/environment.sh
 
+ARGS=$@
+for ARG in $ARGS; do
+    [[ $ARG == '-d' || $ARG == '--deploy' ]] && {
+	ARGS="${ARGS/-d/}";ARGS="${ARGS/--deploy/}"
+	DEPLOY=true
+    }
+    [[ $ARG == '-r' || $ARG == '--remote' ]] && {
+	ARGS="${ARGS/-r/}";ARGS="${ARGS/--remote/}"
+	REMOTE=true
+    }
+done
+[[ -z $REMOTE && -z $DEPLOY ]] || {
+    [[ $DEPLOY == true ]] && $COBBLER_HOME/core/deploy.sh $ARGS
+    [[ $REMOTE == true ]] && $COBBLER_HOME/core/remote.sh $ARGS
+    exit
+}
+
 warn "Cobbler is currently under development"
 if [[ -f $COBBLER_HOME/run/$1.sh ]]; then
     $COBBLER_HOME/run/$1.sh
 elif [[ -f $COBBLER_HOME/run/$1 ]]; then
     $COBBLER_HOME/run/$1
 else
-    fail "Script not found: ${1:-(unspecified)}"
+    fail "Script not found: ${1:-(because no script was specified)}"
 fi
